# Generated by Django 3.2.7 on 2021-09-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0003_alter_comment_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AddField(
            model_name='twitter',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
