# Generated by Django 3.2.7 on 2021-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0004_auto_20210909_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tweets_number',
            field=models.IntegerField(default=0),
        ),
    ]
